### ISSUE TITLE
二十大网络专题学习不能跳转

### ISSUE THREAD

**Issue by feng1992** [johnlin0207/tampermonkey-scripts#1]
https://www.excnpc.com/#/study/subject/detail/1e789cb7-0bf5-419e-ad85-0e9f572074cb

**Comment by johnlin0207** [comment]
更新最新版再试试。

**Comment by johnlin0207** [comment]
> https://www.excnpc.com/#/study/subject/detail/1e789cb7-0bf5-419e-ad85-0e9f572074cb

更新最新版再试试。
